vim.keymap.set("n", "<leader>tt", vim.cmd.Git, { desc = "git: summary window" })
vim.keymap.set("n", "<leader>tl", ":Gclog<CR>", { silent = true, desc = "git: log" })
vim.keymap.set("n", "<leader>tp", ":Git push ", { desc = "git: push with args" })
vim.keymap.set("n", "<leader>tP", function()
  vim.cmd.Git({ "pull", "--rebase" })
end, { desc = "git: pull rebase" })
