local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

local function opts(desc)
  return { desc = "harpoon: " .. desc, noremap = true, silent = true }
end

vim.keymap.set("n", "<leader>bb", ":Telescope harpoon marks<CR>", opts("harpoon: teleport quick menu"))
vim.keymap.set("n", "<leader>ba", function()
  mark.add_file()
end, opts("add file"))
vim.keymap.set("n", "<leader>br", function()
  mark.rm_file()
end, opts("rm file"))
vim.keymap.set("n", "<leader>bc", function()
  mark.clear_all()
end, opts("clear all"))
vim.keymap.set("n", "<leader>1", function()
  ui.nav_file(1)
end, opts("go to mark 1"))
vim.keymap.set("n", "<leader>2", function()
  ui.nav_file(2)
end, opts("go to mark 2"))
vim.keymap.set("n", "<leader>3", function()
  ui.nav_file(3)
end, opts("go to mark 3"))
vim.keymap.set("n", "<leader>4", function()
  ui.nav_file(4)
end, opts("go to mark 4"))
