#!/bin/bash

layout=$(setxkbmap -query | awk '/^layout:/ {print $2}')
if [ "$layout" == "br" ]; then
    notify-send "Keyboard Layout" "US International"
    setxkbmap us -variant alt-intl && ~/.bin/set-keyboard-repeat
else
    notify-send "Keyboard Layout" "BR ABNT2"
    setxkbmap br -variant abnt2 && ~/.bin/set-keyboard-repeat
fi
