#!/usr/bin/env bash

# based on https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

tmux_cmd="tmux -f $HOME/.tmux/tmux.conf"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/repos -maxdepth 3 -type d \( -name worktrees -o -name .git \) -exec dirname {} \; | sort -u | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    $tmux_cmd new-session -s "$selected_name" -c "$selected"
    exit 0
fi
#
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    $tmux_cmd new-session -ds "$selected_name" -c "$selected"
fi

if [[ -n $TMUX ]]; then
    $tmux_cmd switch-client -t "$selected_name"
else
  $tmux_cmd attach-session -d -t "$selected_name"
fi
