#!/bin/bash

if [ $# -eq 0 ]; then
    echo "You must provide a session name"
    exit 1
fi
SESSIONAME=$1

tmux -q has-session -t $SESSIONAME && tmux attach-session -d -t $SESSIONAME || tmux -f ~/.tmux/tmux.conf new-session -s $SESSIONAME
