#!/bin/bash

# GIT tools
git_parse_branch() {
    GIT_VAL=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
    test -z $GIT_VAL || echo "#$GIT_VAL"
}

git_parse_repo() {
    GIT_VAL=$(git config -l 2>/dev/null |grep ^remote.origin.url |awk -F':' '{print$2}' 2>/dev/null)
    test -z $GIT_VAL || echo " $GIT_VAL"
}

lsgit() {
    for F in $(ls ); do
        test ! -d $F && continue;
        test ! -d $F/.git && continue;
        pushd $F >/dev/null && \
            echo -e "$F \033[32m$(git_parse_repo)\033[33m$(git_parse_branch)\033[00m"; \
            popd >/dev/null; done
}

lsgit
