#!/usr/bin/env bash
set -e

if [ $# -eq 0 ]; then
    echo "You must provide a session name"
    exit 1
fi

session_name=$1

if tmux -q has-session -t "$session_name"; then
    exec tmux attach-session -d -t "$session_name"
fi

exec tmux -f "$HOME/.tmux/tmux.conf" new-session -s "$session_name"
