#!/bin/bash

SUB_DIR="journal/daily"
DIR="$ZK_NOTEBOOK_DIR/$SUB_DIR"

DATE_ARG="${1:-$(date +%Y-%m-%d)}"

CURRENT_WEEK=$(date -d "$DATE_ARG" +%V)
CURRENT_YEAR=$(date -d "$DATE_ARG" +%Y)

for FILE in "$DIR"/*.md; do
  FILE_DATE=$(basename "$FILE" .md)

  FILE_WEEK=$(date -d "$FILE_DATE" +%V)
  FILE_YEAR=$(date -d "$FILE_DATE" +%Y)

  if [ "$FILE_WEEK" -eq "$CURRENT_WEEK" ] && [ "$FILE_YEAR" -eq "$CURRENT_YEAR" ]; then
    TASKS=$(sed -n '/# Tasks/,/# Notes/p' "$FILE" | sed '/# Tasks/d' | sed '/# Notes/d')
    if [ -n "$TASKS" ]; then
      echo "[[$SUB_DIR/$FILE_DATE|$FILE_DATE]]"
      echo "$TASKS"
      echo
    fi
  fi
done
