worktree-path = "{{ repo_path }}/../{{ repo }}__worktrees/{{ branch | sanitize }}"
pre-remove= [{ cleanup = "/home/raphael/.bin/worktree-pre-remove {{ worktree_path }} {{ primary_worktree_path }}" }, { pane = "tmux kill-window -t {{ repo }}:wm-{{ branch | sanitize }} 2>/dev/null || true" }]
skip-commit-generation-prompt = true

[pre-start]

[projects]
