# NOTEBOOK SETTINGS
[notebook]
dir = "~/Cloud/Sync/notebook"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = ""

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 6

# Letter case for the random IDs.
id-case = "lower"

# DAILY
[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"

# WEEKLY
[group.weekly]
paths = ["journal/weekly"]

[group.weekly.note]
filename = "{{format-date now '%Y'}}-W{{format-date now '%W'}}"
template = "weekly.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
link-format = "[[{{metadata.id}}|{{title}}]]"

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/usr/bin/fish"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the notes selected interactively among the notes created the last two weeks.
l = "zk edit --interactive"

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

daily = 'zk new --no-input journal/daily'
tomorrow = 'zk new --no-input journal/daily'
weekly = 'zk new --no-input journal/weekly'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
