#!/bin/bash
#
# Author: Raphael P. Ribeiro <raphaelpr01@gmail.com> 

layout=$(setxkbmap -query | grep 'layout' | cut -d ":" -f 2 | tr -d ' ')
variant=$(setxkbmap -query | grep 'variant' | cut -d ":" -f 2 | tr -d ' ')

if [[ ! -z $variant ]]; then
    variant="-$variant"
fi

echo "$layout$variant"
