#!/bin/bash
#
# Author: Raphael P. Ribeiro <raphaelpr01@gmail.com>

ISON=$(wget -q --spider http://google.com && echo ON || echo OFF)
echo $ISON #full_text
echo $ISON #short_text
if [ "$ISON" = "OFF" ]; then # no internet? color will turn red
    echo "#FF0000"
fi
