#!/bin/bash
#
# Author: Raphael P. Ribeiro <raphaelpr01@gmail.com> 

ISON=$(ping -q -w 1 -c 1 www.google.com > /dev/null && echo ON || echo OFF) # IS ON?
echo $ISON #full_text
echo $ISON #short_text
if [ "$ISON" = "OFF" ]; then # no internet? color will turn red
    echo "#FF0000"
fi
