#!/usr/bin/env bash
#=========================================================================================
#
#   DESCRIPTION: Retrieve AWS keys from clipboard and paste to your AWS credentials file
#   DEPENDENCIES: libnotify, xclip
#
#=========================================================================================

AWS_ACCOUNTS=$HOME/.aws_accounts
AWS_CREDENTIALS=$HOME/.aws/credentials

[[ ! -x "$(command -v notify-send)" ]] && echo "Error: libnotify is not installed" >&2 && exit 1
[[ ! -x "$(command -v xclip)" ]] && notify "Error: xclip is not installed" >&2 && exit 1

tmpfile=$(mktemp)

# redirect clipboard output to tmp file
xclip -selection clipboard -o > $tmpfile

# retrieve account number
aws_number=$(egrep -o "[0-9]{12}" $tmpfile)

# if there is no account number, exit
if [[ -z $aws_number ]]; then
    notify-send "AWS credentials" "Paste failed"
    rm $tmpfile
    exit 1
fi

# retrieve name by account number
aws_name=$(grep $aws_number $AWS_ACCOUNTS | awk '{ print $2 }')

# replace profile name
sed -i "1s/.*/[$aws_name]/" $tmpfile
echo -e "\n$(tail -n 1 $tmpfile | sed 's/aws_session_token/aws_security_token/g')" >> $tmpfile

# if profile already exists, remove it
sed -i "/$aws_name/,+5d" $AWS_CREDENTIALS

# paste profile
echo "" >> $AWS_CREDENTIALS
cat $tmpfile >> $AWS_CREDENTIALS

# nice formatting: add blank lines between profiles
sed -i -e "/^$/d" -e "s/^\[.*\]\$/\n&/g" $AWS_CREDENTIALS
sed -i '1d' $AWS_CREDENTIALS

rm $tmpfile

notify-send "AWS credentials" "$aws_name pasted"
