#!/bin/bash
#=========================================================================================
#
#   DESCRIPTION: Retrieve AWS keys from clipboard and paste to your AWS credentials file
#   DEPENDENCIES: libnotify, xclip
#
#=========================================================================================

AWS_ACCOUNTS=$HOME/.aws_accounts
AWS_CREDENTIALS=$HOME/.aws/credentials
TMPFILE=$(mktemp)

# redirect clipboard output to tmp file
xclip -selection clipboard -o > $TMPFILE

# retrieve account number
aws_number=$(egrep -o "[0-9]{12}" $TMPFILE)

# if there is no account number, exit
if [[ -z $aws_number ]]; then
   notify-send "AWS Credentials" "Paste failed"
    exit 1
fi

# retrieve name by account number
aws_name=$(grep $aws_number $AWS_ACCOUNTS | awk '{ print $2 }')

# replace profile name
sed -i "1s/.*/[$aws_name]/" $TMPFILE

# if profile already exists, remove it
sed -i "/$aws_name/,+4d" $AWS_CREDENTIALS

# paste profile
echo "" >> $AWS_CREDENTIALS
cat $TMPFILE >> $AWS_CREDENTIALS

# nice formatting: add blank lines between profiles
sed -i -e "/^$/d" -e "s/^\[.*\]\$/\n&/g" $AWS_CREDENTIALS
sed -i '1d' $AWS_CREDENTIALS

rm $TMPFILE

notify-send "AWS credentials" "$aws_name pasted"
