#!/bin/bash

# It rotates all AWS access keys located in aws credentials file

# Dependencies: 
# - aws-rotate-keys: https://github.com/Fullscreen/aws-rotate-key

aws_credentials_file=$HOME/.aws/credentials
aws_profile_names=$(grep '^\[.*]' $aws_credentials_file | tr -d "[]")
logfile=/tmp/aws-rotate-all-keys.log
    
printf "\n##################################################################\n\n" |& tee -a $logfile
printf "[$(date +"%d/%m/%Y:%H:%M:%S")] Starting rotate AWS access keys...\n" |& tee -a $logfile
printf "\n##################################################################\n\n" |& tee -a $logfile

for p in $aws_profile_names; do
    aws-rotate-key -y -profile $p |& tee -a $logfile
done

printf "\n\n##################################################################\n\n" |& tee -a $logfile
printf "[$(date +"%d/%m/%Y:%H:%M:%S")] Finished! Syncing $aws_credentials_file from localhost to $SSH_HOME_HOST\n\n" |& tee -a $logfile

while true; do
    rsync -avz -e "ssh -p $SSH_HOME_PORT" $aws_credentials_file $SSH_HOME_HOST:$aws_credentials_file
    if [ "$?" = "0" ] ; then
        printf "[$(date +"%d/%m/%Y:%H:%M:%S")] Rsync completed\n" |& tee -a $logfile
        printf "\n##################################################################\n\n" |& tee -a $logfile
        exit
    else
        printf "[$(date +"%d/%m/%Y:%H:%M:%S")] Rsync failure. Retrying...\n" |& tee -a $logfile
        sleep 5
    fi
done

