#!/bin/bash

# This file contains install/configure instructions that I use on Arch/Manjaro Linux

export EDITOR=vim
PKGLIST=../.pkglist

# pacman update and dependencies
sudo pacman -Syu --needed

if ! sudo pacman -Q pcaur > /dev/null; then
  echo "pacaur not installed! Install it manually."
  exit 1
fi

sudo pacman -S --noconfirm --needed vim python python-pip fish make cmake gcc fakeroot patch dnsutils nodejs npm ruby ruby-rdoc ruby-docs wget unzip cronie git

# sync sensitive - not versioned - dotfiles
ln -sf ~/Dropbox ~/Cloud
ln -sf ~/Cloud/sync/local_share_fish ~/.local/share/fish
ln -sf ~/Cloud/sync/ptpython_history ~/.ptpython/history
ln -sf ~/Cloud/sync/envsen ~/.envsen
ln -sf ~/Cloud/sync/ssh_config ~/.ssh/config
ln -sf ~/Cloud/sync/copyq.conf ~/.config/copyq/copyq.conf
ln -sf ~/Cloud/sync/krew ~/.krew

# install cron jobs
crontab <<EOF
# Update duck dns
*/5 * * * * ~/Cloud/sync/scripts/duck.sh >/dev/null 2>&1
EOF

# install pip / python packages
sudo pip install tmuxp virtualenv neovim virtualfish flake8 saws ptpython ipython boto3 yamllint

# aws-fuzzy
[[ ! -d ~/.virtualenvs ]]  && mkdir ~/.virtualenvs
cd ~/.virtualenvs
virtualenv -p python3 ~/.virtualenvs/aws-fuzzy
source ~/.virtualenvs/aws-fuzzy/bin/activate || source ~/.virtualenvs/aws-fuzzy/bin/activate.fish
pip install https://github.com/raphapr/aws-fuzzy-finder/archive/v0.3.6.zip
deactivate

# npm prefix configuration
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

# npm packages
npm install -g git-recent jsonlint

# homesick: dotfiles version control
export PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
gem install homesick

# install plug vim
if [ ! -d ~/.config/nvim/autoload/plug.vim ]; then
  echo "[ bootstrap ] :: install plug.vim"
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  echo "[ bootstrap ] :: plug.vim already installed!"
fi

# install git completion for bash
if [ ! -f ~/.git-completion.bash ]; then
  echo "[ bootstrap ] :: install git-completion.bash"
  wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O ~/.git-completion.bash
else
  echo "[ bootstrap ] :: git-completion.bash already installed!"
fi

# install kubectl completion for fish shell
mkdir -p ~/.config/fish/completions
pushd ~/.config/fish
git clone https://github.com/evanlucas/fish-kubectl-completions
ln -s ../fish-kubectl-completions/completions/kubectl.fish completions/
popd

# install fzf
if [ ! -d ~/.fzf ]; then
  echo "[ bootstrap ] :: Install fzf"
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
else
  echo "[ bootstrap ] :: fzf already installed!"
fi

# install powerline-fonts
if [ ! -d ~/.fonts ]; then
  echo "[ bootstrap ] :: Install powerline-fonts"
  git clone https://github.com/powerline/fonts.git /tmp/fonts
  sh /tmp/fonts/install.sh
  ln -s ~/.local/share/fonts ~/.fonts
else
  echo "[ bootstrap ] :: powerline-fonts already installed!"
fi

# symlink tmux conf
ln -sf ~/.tmux.conf ~/.tmux/tmux.conf

# tmux plugins
mkdir -p ~/.tmux/plugins
git clone https://github.com/laktak/extrakto ~/.tmux/plugins/extrakto

# install tmux-xpanes
wget https://raw.githubusercontent.com/greymd/tmux-xpanes/master/bin/xpanes -O /tmp/xpanes
sudo install -m 0755 /tmp/xpanes /usr/local/bin/xpanes
rm -rf ~/tmp/xpanes

# install pkg list

echo "[ bootstrap ] :: Install pacman/aur packages"
for PKG in $(cat $PKGLIST); do
    pacaur -S --needed --noedit --noconfirm $PKG || echo "$PKG failed." >> $PKGLOG
done
