#!/bin/bash

PIDFILE=/tmp/controller.pid

case "$1" in

status)
        if [ -e /tmp/controller.pid ]; then
            echo "Controller daemon running..."
        else
            echo "Controller daemon not running..."
        fi
        ;;
stop)
        echo "Stop controller daemon..."
        sudo pkill ds4drv && rm -rf $PIDFILE
        sudo rm -rf /dev/input/js0
        ;;
start)
        echo "Start controller daemon..."
        ds4drv --daemon --hidraw --emulate-xpad
        pgrep "ds4drv" >> /tmp/controller.pid
        sleep 1
        sudo mv /dev/input/js1 /dev/input/js0
        ;;
restart)
        stop
        sleep 1
        start
        ;;
esac
