#!/bin/bash

# Criar arquivo /usr/share/applications/magnet.desktop com conteúdo:
#
#    [Desktop Entry]
#    Name=Transmission
#    Type=Application
#    Comment=Open a torrent file to transmission
#    Exec=/home/raphael/.bin/cptowatch %U
#    Categories=Network;WebBrowser;
#    MimeType=application/x-bittorrent;
#
# Depois associar em ~/.local/share/applications/mimeapps.list

cp "$1" ~/Torrents/Watch/ && notify-send "Torrent adicionado" "$(basename "$1")"
