#!/bin/bash

file=$HOME/.asoundrc

if [ -e $file ]; then
    mv $file $HOME/.asoundrc.OFF
    sudo alsactl restore
    killall notify-osd
    notify-send "HDMI AUDIO" "OFF" -i /usr/share/icons/Numix/32/categories/applications-multimedia.svg
else
    mv $HOME/.asoundrc.OFF $file
    sudo alsactl restore
    killall notify-osd
    notify-send "HDMI AUDIO" "ON" -i /usr/share/icons/Numix/32/categories/applications-multimedia.svg
fi
