#!/bin/bash


layout=$(setxkbmap -query | awk 'FNR == 3 {print $2}')
variant=$(setxkbmap -query | awk 'FNR == 4 {print $2}')
klayout="$layout-$variant"
if [ "$klayout" == "br-abnt2" ]; then
    setxkbmap us -variant alt-intl "default" && xmodmap ~/.Xmodmap
    notify-send "Keyboard Layourt" "US International"
else
    setxkbmap br -variant abnt2 "default" && xmodmap ~/.Xmodmap
    notify-send "Keyboard Layourt" "BR ABNT2"
fi
