#!/bin/bash

layout=$(setxkbmap -query | grep 'layout' | cut -d ":" -f 2 | tr -d ' ')
variant=$(setxkbmap -query | grep 'variant' | cut -d ":" -f 2 | tr -d ' ')
klayout="$layout-$variant"
if [ "$klayout" == "br-abnt2" ]; then
    notify-send "Keyboard Layourt" "US International"
    setxkbmap us -variant alt-intl "default" && xmodmap ~/.Xmodmap
else
    notify-send "Keyboard Layourt" "BR ABNT2"
    setxkbmap br -variant abnt2 "default" && xmodmap ~/.Xmodmap
fi
