#!/bin/bash

pid=$(pidof xautolock)
if [ -z $pid ]; then # Se não está rodando
    xautolock -time 4 -locker "i3lock -c 000000" &
    killall notify-osd
    notify-send "Screensaver" "ON"
else
    pkill xautolock
    killall notify-osd
    notify-send "Screensaver" "OFF"
fi
