#!/bin/bash

pid=$(pidof xfce4-power-manager)
if [ -z $pid ]; then # Se não está rodando
    xfce4-power-manager
    xautolock -time 4 -locker "i3lock -c 000000" &
    killall xfce4-notifyd && notify-send "Gerenciamento de energia" "ON" -t 6
else
    kill -9 $pid
    pkill xautolock
    killall xfce4-notifyd && notify-send "Gerenciamento de energia" "OFF" -t 6
fi
