#!/usr/bin/env bash

SOURCE_DIR="$(dirname ${BASH_SOURCE[0]})"
SELECTED_INDEX="$(copyq eval "$(cat $(which copyq_all))" | rofi -dmenu -format i -p "copyq: " -theme ~/.config/rofi/bala.rasi)"

if [ "$SELECTED_INDEX" -eq "$SELECTED_INDEX" ] 2>/dev/null; then
   copyq select "$SELECTED_INDEX"
fi
