#!/bin/bash

HISTORY_FILE="$HOME/.local/share/fish/fish_history"
SELECTED=$(cat $HISTORY_FILE | grep "cmd" | sed 's/^- cmd: //g' | sed 's/^ //g' | tac | nl | rofi -dmenu -font "hack 10" -p "history: " -theme ~/.config/rofi/bala.rasi)

echo -n $SELECTED | sed 's/^[0-9]\+ //g' | xclip -sel clip
