#!/bin/bash

if test -z $1; then
		SCROT_ARG=""
elif test $1 == "-s"; then
		SCROT_ARG="-s"
else
		echo "Opção inválida: $1"
		exit 1
fi

SCRDIR="$HOME/Imagens/Screenshots"

scrot $SCROT_ARG $SCRDIR/%b%d::%H%M%S.png
paplay ~/.sounds/ss.wav
xclip -selection c -t image/png $SCRDIR/$(ls -Art $SCRDIR | tail -n 1)
