#!/usr/bin/env bash
set -o pipefail

current=$(tmux display-message -p '#{session_name}:#{window_index}')
if ! target="$({
  tmux list-windows -a -F '#{session_name}:#{window_index} #{window_name} (#{window_panes} panes)'
} | awk -v current="$current" '$1 != current' |
  fzf-tmux -p 60%,50% --prompt 'Move pane to window: ' |
  cut -d' ' -f1)"; then
  exit 0
fi

[ -n "$target" ] && tmux join-pane -t "$target"
