blacklist = ["scratchpad-journal", '_worktrees(/.*)?$']

[[session]]
name = "raphael"
path = "~"

[[session]]
name = "screen2"
path = "~"

[[session]]
name = "chezmoi"
path = "~/.local/share/chezmoi"

[[session]]
name = "pi-conf"
path = "~/.pi"

[[session]]
name = "nvim-conf"
path = "~/.config/nvim/lua/raphapr"

[[session]]
name = "tmux-conf"
path = "~/.tmux"
