require("raphapr.settings")
require("raphapr.autocmds")
require("raphapr.utils")
require("raphapr.lazy")
require("raphapr.remaps")
require("luasnip.loaders.from_lua").load({ paths = { "~/.config/nvim/lua/raphapr/luasnip/" } })
