[tools]
node='20.5.0'
terraform='1.5.7'
opentofu='1.7.2'
golang='1.23'
kubectl='1.29.0'
shellcheck='0.8.0'
helm='3.8.2'
terraform-ls='0.28.0'
yazi = "latest"
'cargo:eza'='latest'
'cargo:tmux-sessionizer'='latest'
'cargo:atuin'='latest'
'cargo:yazi-fm'='latest'
"cargo:yazi-cli"= 'latest'
'npm:git-recent'='latest'
'npm:jsonlint'='latest'
'npm:neovim'='latest'
go = "1.23"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
