[tools]
node= "latest"
terraform='1.5.7'
opentofu='1.7.2'
go= "1.24"
kubectl='1.29.0'
shellcheck='0.8.0'
helm='3.8.2'
terraform-ls='0.28.0'
yazi = "latest"
stern = "1.33.0"
'cargo:eza'='latest'
'cargo:tmux-sessionizer'='latest'
'cargo:atuin'='latest'
'cargo:yazi-fm'='latest'
"cargo:yazi-cli"= 'latest'
"cargo:kanata"= 'latest'
"cargo:fsel"= 'latest'
'npm:git-recent'='latest'
'npm:jsonlint'='latest'
'npm:neovim'='latest'
'npm:opencode-ai'='latest'
'go:golang.org/x/tools/gopls' = '0.20.0'

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
